version: '3.7'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - network
    ports:
      - "8080:8080"
      - "443:443"
      - "6001:6001"

  database:
    image: bitnami/mariadb:latest
    container_name: database
    restart: unless-stopped
    expose:
      - 3308
    ports:
      - "3308:3308"
    volumes:
      - ./.docker/database/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MARIADB_ROOT_PASSWORD=root
    networks:
      - network

#MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quizapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql/
    networks:
      - network


networks:
  network:
    name: network
    driver: bridge